window.questions = [
  { id: 1, title: "你覺得哪一側臉整體看起來更“大”？", observation: "請看正面自然表情照片，重點看中下面部整體佔位感，不是隻看某一小塊。這裏的“大”，包括一側更寬、一側更鼓、一側更有存在感、一側下頜緣更外擴。", options: [{ text: "左側更大", value: "left_bigger" }, { text: "右側更大", value: "right_bigger" }, { text: "兩側差不多或看不出", value: "similar" }] },
  { id: 2, title: "你覺得哪一側更“緊、硬、鼓”？", observation: "請用手輕摸兩側咬肌、臉頰和下頜緣，或者看照片。這裏不是問哪邊骨頭高，而是問哪邊更像更繃、更厚、更頂、更容易顯得結實或發硬。", options: [{ text: "左側更明顯", value: "left_tight" }, { text: "右側更明顯", value: "right_tight" }, { text: "不明顯或說不清", value: "not_clear" }] },
  { id: 3, title: "你覺得哪一側更像“被拉偏”而不是“更厚”？", observation: "重點看一側嘴角像被斜着拖走，一側蘋果肌更高更緊，一側法令紋更深，一側下頜線更繃更利，整張臉像沿一條斜線被擰過。", options: [{ text: "左側更像被拉偏", value: "left_pulled" }, { text: "右側更像被拉偏", value: "right_pulled" }, { text: "沒有這種感覺或不確定", value: "not_sure" }] },
  { id: 4, title: "把頭自然擺正後，左右差異會不會減輕？", observation: "不是刻意挺直，也不是抬頭收下巴，只是把平時習慣歪向一邊的頭輕輕回到中立位，再看左右差異。", options: [{ text: "明顯減輕", value: "significantly_reduced" }, { text: "有一點減輕", value: "slightly_reduced" }, { text: "基本沒變化", value: "no_change" }, { text: "不確定", value: "uncertain" }] },
  { id: 5, title: "平躺後，左右差異會不會減輕？", observation: "平躺時儘量不用高枕，不咬牙，不做表情，看臉部左右差異是否比站立時減輕。", options: [{ text: "明顯減輕", value: "significantly_reduced_lying" }, { text: "有一點減輕", value: "slightly_reduced_lying" }, { text: "基本沒變化", value: "no_change_lying" }, { text: "不確定", value: "uncertain_lying" }] },
  { id: 6, title: "微笑或說話時，兩邊差異會不會更明顯？", observation: "不要只看靜態照。請看自己微笑、說話、露齒時，一側口角是否更容易上去，一側是否更慢，一側是否明顯更使不上勁或更漏。", options: [{ text: "明顯更明顯", value: "significantly_more_obvious" }, { text: "有一點更明顯", value: "slightly_more_obvious" }, { text: "差不多", value: "similar_dynamic" }, { text: "不確定", value: "uncertain_dynamic" }] },
  { id: 7, title: "你更像是哪一種情況？", observation: "A 類是一側更厚、更硬、更鼓，像“肉多或出力多”；B 類是一側更像被斜着拉偏，位置不對，不只是厚薄差。", options: [{ text: "更像A厚硬鼓", value: "type_a" }, { text: "更像B被拉偏位置變了", value: "type_b" }, { text: "兩種都有", value: "both_types" }, { text: "都不明顯", value: "neither" }] },
  { id: 8, title: "你是否長期有一側咀嚼更多、咬得更用力？", observation: "不是偶爾，而是長期形成習慣。比如總愛用同一邊喫東西，一邊咬更順手，一邊更容易累或更容易發達。", options: [{ text: "經常", value: "often_chew" }, { text: "偶爾", value: "sometimes_chew" }, { text: "沒有", value: "never_chew" }, { text: "不確定", value: "uncertain_chew" }] },
  { id: 9, title: "你是否感覺一側表情啓動更慢、控制更差？", observation: "重點看微笑時一側慢半拍，鼓氣一側更容易漏，閉眼一側更不全，說話時口角更偏一邊。", options: [{ text: "明顯有", value: "obvious_control" }, { text: "輕微有", value: "slight_control" }, { text: "沒有", value: "no_control" }, { text: "不確定", value: "uncertain_control" }] },
  { id: 10, title: "你是否長期固定同一側側睡、托腮或歪頭？", observation: "只算長期固定習慣，不算偶爾，包括固定側睡、固定單手托腮、長時間一邊看手機、總把頭偏向一邊。", options: [{ text: "經常", value: "often_posture" }, { text: "偶爾", value: "sometimes_posture" }, { text: "沒有", value: "never_posture" }, { text: "不確定", value: "uncertain_posture" }] },
  { id: 11, title: "你是否明顯有高低肩、歪脖子或一側頸部總更緊？", observation: "看正面或照鏡子，重點看肩膀是否一高一低，頭是否總偏向一邊，一側頸側是否總更緊更短，感覺臉像被脖子和肩膀帶偏。", options: [{ text: "明顯有", value: "obvious_posture_issue" }, { text: "偶爾有", value: "sometimes_posture_issue" }, { text: "沒有", value: "no_posture_issue" }, { text: "不確定", value: "uncertain_posture_issue" }] },
  { id: 12, title: "你是否有舊傷史、正畸史，或咬合/下巴軌跡長期不順？", observation: "這裏不是讓用戶自我診斷，只看是否有這些背景：正在或曾經正畸，下頜面部頸肩外傷史，張口或閉口軌跡長期不順，咬合總覺得偏一邊。", options: [{ text: "明顯有", value: "obvious_history" }, { text: "有一點或不太確定", value: "slight_history" }, { text: "沒有", value: "no_history" }] }
];
